Update cook.yml

diff --git a/.github/workflows/cook.yml b/.github/workflows/cook.yml
--- a/.github/workflows/cook.yml
+++ b/.github/workflows/cook.yml
@@ -14,7 +14,8 @@ on:
       bootstrap:
         description: 'If "true" bootstraps freetype/harfbuzz circular dependency and r-base-dev - required for real distribution. Set to "false" if you are testing a specific recipe and want to save time.'
         required: false
-        default: 'true'
+        type: boolean
+        default: true
 
 jobs:
   cook:
@@ -32,7 +33,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ 'macOS-13', 'macos-14' ]
+        os: [ 'macos-13', 'macos-14' ]
 
     steps:
       - uses: actions/checkout@v2
@@ -42,7 +43,7 @@ jobs:
           ## Remove unwanted local files
           sudo mkdir /usr/local/.disabled && sudo mkdir -p /opt/R/`uname -m`/bin && sudo chown -R $USER /opt/R
           sudo mv /usr/local/* /usr/local/.disabled/ && sudo rm -rf /opt/homebrew
-          echo /opt/R/`uname -m`/bin: > .PATH && cat $GITHUB_PATH >> .PATH && cat .PATH > $GITHUB_PATH && rm .PATH
+          echo /opt/R/`uname -m`/bin > .PATH && cat $GITHUB_PATH >> .PATH && cat .PATH > $GITHUB_PATH && rm .PATH
           echo "ARCH=$(uname -m)" > $GITHUB_ENV
 
       - name: Setup toolchain
@@ -52,7 +53,7 @@ jobs:
           if [ -n "$SDKURL" ]; then
             echo Installing SDK..
             sdkname=$(curl -sfSL "$SDKURL" | sudo tar vxz -C /Library/Developer/CommandLineTools/SDKs 2>&1 | sed -n '1s:^x ::p' | sed -E 's:/*$::' )
-            if ! echo $sdkname | grep ^MacOSX; then echo "::error:: SDKURL is not valid, the tar ball must contain MacOSX*.sdk directory" >&2; exit 1; fi
+            if ! echo $sdkname | grep ^MacOSX; then echo "::error:: SDKURL is not valid, the tar ball must contain just the MacOSX*.sdk directory" >&2; exit 1; fi
             SDKROOT="/Library/Developer/CommandLineTools/SDKs/$sdkname"
             MACOSX_DEPLOYMENT_TARGET="$(echo $sdkname | sed 's:MacOSX::' | sed 's:[.]sdk$::')"
             OS_VER=$(echo $MACOSX_DEPLOYMENT_TARGET | awk '{ if ($1 >= 11) print int($1+9); else print int(substr($1,4))+4 }')
@@ -88,7 +89,7 @@ jobs:
         run: ./build.sh -f pkgconfig xz
 
       - name: Bootstrap freetype/harfbuzz circular dependency
-        if: ${{ github.event.inputs.bootstrap }} == 'true'
+        if: ${{ inputs.bootstrap }}
         run: |
           ./build.sh freetype
           ./build.sh harfbuzz
@@ -96,7 +97,7 @@ jobs:
           ./build.sh harfbuzz
 
       - name: Build r-base-dev
-        if: ${{ github.event.inputs.bootstrap }} == 'true'
+        if: ${{ inputs.bootstrap }}
         run: ./build.sh r-base-dev
 
       - name: Build ${{ github.event.inputs.target }}
